[package]
name = "Counter"
version = "0.0.0"

[dependencies]
AptosFramework = { local = "../../aptos-core/aptos-move/framework/aptos-framework" }

[addresses]
AptosCounter = "0xAF49AB5799B9CEF57C363337AA8B71AE3A9EE91512005C3517C95F2944EE1364"
